CREATE TYPE "public"."SellerDecision" AS ENUM ('PENDING', 'ACCEPTED', 'RETEST_REQUESTED');

ALTER TABLE "public"."QualityInspection"
  ADD COLUMN "basePrice" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "gradePrice" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "storageCharge" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "labourCharge" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "otherCharge" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "bonus" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "bonusReason" TEXT,
  ADD COLUMN "suggestion" TEXT,
  ADD COLUMN "sellerDecision" "public"."SellerDecision" NOT NULL DEFAULT 'PENDING',
  ADD COLUMN "sellerDecisionAt" TIMESTAMP(3),
  ADD COLUMN "finalizedAt" TIMESTAMP(3),
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
