"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ShoppingCart } from "lucide-react";
import { LoggedInNavbar } from "../../../component/LoggedInNavbar";

const format = (value) => Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 });

export default function CenterMarketplacePage() {
  const [listings, setListings] = useState([]); const [quantities, setQuantities] = useState({}); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [working, setWorking] = useState("");
  function load() { fetch("/api/center/trades/market", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.message); return payload; }).then((payload) => setListings(payload.listings)).catch((requestError) => setError(requestError.message)); }
  useEffect(() => { load(); }, []);
  async function request(listingId) { setWorking(listingId); setError(""); setMessage(""); try { const response = await fetch("/api/center/trades", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listingId, quantity: quantities[listingId] }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); setMessage(payload.message); load(); } catch (requestError) { setError(requestError.message); } finally { setWorking(""); } }
  return <><LoggedInNavbar /><main className="min-h-screen bg-[#f6f8f4] p-5 sm:p-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-wider text-green-700">CENTER-TO-CENTER TRADING</p><h1 className="mt-1 text-3xl font-black">Buy soybean from another center</h1><p className="mt-2 text-gray-600">Reserve stock, request physical check, negotiate, and transfer it into your center storage after settlement.</p></div><Link href="/center/trades" className="rounded-xl border border-green-200 bg-white px-4 py-2.5 text-sm font-bold text-green-800">View trade requests</Link></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>}{message && <p className="mt-5 rounded-xl bg-green-50 p-3 font-bold text-green-800">{message}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{listings.map((listing) => { const available = Number(listing.availableQty) - Number(listing.reservedQty); return <article key={listing.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">{listing.center.name}</h2><p className="text-sm text-gray-600">{listing.center.district}, {listing.center.state}</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-black text-green-800">Grade {listing.grade}</span></div><p className="mt-4 text-2xl font-black text-green-800">{format(available)} qtl available</p><p className="mt-1 font-bold">₹{format(listing.pricePerQuintal)} / quintal</p><p className="mt-2 text-sm text-gray-600">Order by {new Date(listing.availableUntil).toLocaleDateString("en-IN")} · Pickup {new Date(listing.pickupStart).toLocaleDateString("en-IN")} – {new Date(listing.pickupEnd).toLocaleDateString("en-IN")}</p><div className="mt-5 flex gap-2"><input min="0.01" max={available} step="0.01" type="number" value={quantities[listing.id] || ""} onChange={(event) => setQuantities((current) => ({ ...current, [listing.id]: event.target.value }))} placeholder="Quantity (qtl)" className="min-w-0 flex-1 rounded-lg border p-2" /><button disabled={working === listing.id} onClick={() => request(listing.id)} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-50"><ShoppingCart size={16} />{working === listing.id ? "Sending…" : "Request"}</button></div></article>; })}</div>{!error && listings.length === 0 && <p className="mt-6 rounded-2xl bg-white p-6 text-gray-600 shadow-sm">No other center currently has soybean stock available for inter-center trade.</p>}</div></main></>;
}
