"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ClipboardCheck, Handshake, XCircle } from "lucide-react";
import { LoggedInNavbar } from "../../../component/LoggedInNavbar";

const format = (value) => Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 });
const labels = { ORDERED: "Stock reserved", PHYSICAL_CHECK_PENDING: "Physical-check request pending", PHYSICAL_CHECKED: "Physical check approved", CONFIRMED: "Price offer awaiting seller", PAID: "Settlement successful", CANCELLED: "Cancelled" };

export default function CenterTradesPage() {
  const [data, setData] = useState(null); const [forms, setForms] = useState({}); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [working, setWorking] = useState("");
  function load() { fetch("/api/center/trades", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.message); return payload; }).then(setData).catch((requestError) => setError(requestError.message)); }
  useEffect(() => { load(); }, []);
  function formFor(id, trade) { return forms[id] || { quantity: trade.finalQty || trade.requestedQty, proposedPrice: trade.proposedPrice || trade.listing.pricePerQuintal, negotiationNote: trade.negotiationNote || "" }; }
  function setField(id, key, value) { setForms((current) => ({ ...current, [id]: { ...current[id], [key]: value } })); }
  async function update(trade, action) { setWorking(`${trade.id}-${action}`); setError(""); setMessage(""); try { const form = formFor(trade.id, trade); const response = await fetch(`/api/center/trades/${trade.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...form }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message); setMessage(payload.message); load(); } catch (requestError) { setError(requestError.message); } finally { setWorking(""); } }
  if (!data && !error) return <main className="grid min-h-screen place-items-center font-bold text-gray-600">Loading center trades…</main>;
  const trades = data?.trades || []; const centerId = data?.centerId;
  const purchases = trades.filter((trade) => trade.buyerCenterId === centerId); const sales = trades.filter((trade) => trade.sellerCenterId === centerId);
  function TradeCard({ trade, mode }) { const isBuyer = mode === "BUY"; const form = formFor(trade.id, trade); const busy = (action) => working === `${trade.id}-${action}`; return <article className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-wider text-green-700">{isBuyer ? "BUYING CENTER" : "SELLING CENTER"}</p><h2 className="mt-1 text-lg font-black">{isBuyer ? trade.sellerCenter.name : trade.buyerCenter.name}</h2><p className="text-sm text-gray-600">Soybean · Grade {trade.listing.grade} · {isBuyer ? trade.sellerCenter.district : trade.buyerCenter.district}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${trade.status === "PAID" ? "bg-green-100 text-green-800" : trade.status === "CANCELLED" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800"}`}>{labels[trade.status]}</span></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-3"><p><span className="font-bold">Requested:</span> {format(trade.requestedQty)} qtl</p><p><span className="font-bold">Final:</span> {trade.finalQty ? `${format(trade.finalQty)} qtl` : "Pending"}</p><p><span className="font-bold">Offer:</span> {trade.proposedPrice ? `₹${format(trade.proposedPrice)}/qtl` : "Pending"}</p></div>{trade.negotiationNote && <p className="mt-3 rounded-lg bg-gray-50 p-3 text-sm text-gray-700"><span className="font-bold">Negotiation note:</span> {trade.negotiationNote}</p>}{trade.cancelReason && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700"><span className="font-bold">Reason:</span> {trade.cancelReason}</p>}
    {isBuyer && trade.status === "ORDERED" && <div className="mt-5 flex flex-wrap gap-2"><button disabled={busy("REQUEST_PHYSICAL_CHECK")} onClick={() => update(trade, "REQUEST_PHYSICAL_CHECK")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><ClipboardCheck size={16} />{busy("REQUEST_PHYSICAL_CHECK") ? "Sending…" : "Request physical check"}</button><button onClick={() => update(trade, "CANCEL")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Cancel</button></div>}
    {isBuyer && trade.status === "PHYSICAL_CHECK_PENDING" && <div className="mt-5 flex flex-wrap gap-2"><p className="rounded-lg bg-amber-50 px-3 py-2 text-sm font-bold text-amber-800">Waiting for selling center to approve the physical check.</p><button onClick={() => update(trade, "CANCEL")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Cancel</button></div>}
    {isBuyer && trade.status === "PHYSICAL_CHECKED" && <div className="mt-5 rounded-xl border border-green-100 bg-green-50 p-4"><p className="font-black text-green-900">Physical check complete — send negotiated offer</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><input min="0.01" step="0.01" type="number" value={form.quantity} onChange={(event) => setField(trade.id, "quantity", event.target.value)} placeholder="Final quantity" className="rounded-lg border bg-white p-2" /><input min="0.01" step="0.01" type="number" value={form.proposedPrice} onChange={(event) => setField(trade.id, "proposedPrice", event.target.value)} placeholder="Price / qtl" className="rounded-lg border bg-white p-2" /><input value={form.negotiationNote} onChange={(event) => setField(trade.id, "negotiationNote", event.target.value)} placeholder="Negotiation note" className="rounded-lg border bg-white p-2" /></div><div className="mt-3 flex gap-2"><button disabled={busy("SUBMIT_OFFER")} onClick={() => update(trade, "SUBMIT_OFFER")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><Handshake size={16} />{busy("SUBMIT_OFFER") ? "Sending…" : "Send final offer"}</button><button onClick={() => update(trade, "CANCEL")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Cancel</button></div></div>}
    {!isBuyer && trade.status === "PHYSICAL_CHECK_PENDING" && <div className="mt-5 flex flex-wrap gap-2"><button disabled={busy("GRANT_PHYSICAL_CHECK")} onClick={() => update(trade, "GRANT_PHYSICAL_CHECK")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><ClipboardCheck size={16} />{busy("GRANT_PHYSICAL_CHECK") ? "Approving…" : "Allow physical check"}</button><button onClick={() => update(trade, "REJECT_SALE")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Decline</button></div>}
    {!isBuyer && trade.status === "CONFIRMED" && <div className="mt-5 flex flex-wrap gap-2"><button disabled={busy("ACCEPT_SALE")} onClick={() => update(trade, "ACCEPT_SALE")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><CheckCircle2 size={16} />{busy("ACCEPT_SALE") ? "Settling…" : "Accept offer & transfer stock"}</button><button disabled={busy("REJECT_SALE")} onClick={() => update(trade, "REJECT_SALE")} className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700"><XCircle size={16} />Decline offer</button></div>}
  </article>; }
  return <><LoggedInNavbar /><main className="min-h-screen bg-[#f6f8f4] p-5 sm:p-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-wider text-green-700">CENTER-TO-CENTER TRADING</p><h1 className="mt-1 text-3xl font-black">Trade requests & settlement history</h1><p className="mt-2 text-gray-600">Both centers can track physical checks, negotiated offers, settlement, and storage transfer here.</p></div><Link href="/center/market" className="rounded-xl bg-green-700 px-4 py-2.5 text-sm font-bold text-white">Buy from centers</Link></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>}{message && <p className="mt-5 rounded-xl bg-green-50 p-3 font-bold text-green-800">{message}</p>}<section className="mt-7"><h2 className="text-2xl font-black">Purchases from other centers</h2><div className="mt-4 space-y-4">{purchases.map((trade) => <TradeCard key={trade.id} trade={trade} mode="BUY" />)}{purchases.length === 0 && <p className="rounded-2xl bg-white p-6 text-gray-600 shadow-sm">No purchases from another center yet.</p>}</div></section><section className="mt-8"><h2 className="text-2xl font-black">Sales to other centers</h2><div className="mt-4 space-y-4">{sales.map((trade) => <TradeCard key={trade.id} trade={trade} mode="SELL" />)}{sales.length === 0 && <p className="rounded-2xl bg-white p-6 text-gray-600 shadow-sm">No other center has requested your stock yet.</p>}</div></section></div></main></>;
}
