"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, CheckCircle2, ClipboardCheck, Handshake, XCircle } from "lucide-react";
import { LoggedInNavbar } from "@/component/LoggedInNavbar";

const format = (value) => Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 });
const statusLabel = { ORDERED: "Stock reserved", PHYSICAL_CHECK_PENDING: "Physical check requested", PHYSICAL_CHECKED: "Physical check approved", CONFIRMED: "Final offer pending", PAID: "Settlement successful", CANCELLED: "Cancelled" };

export default function CenterMarketDetailPage() {
  const { id: buyerCenterId, sellerCenterId } = useParams();
  const [data, setData] = useState({ listings: [], trades: [] }); const [forms, setForms] = useState({}); const [message, setMessage] = useState({ text: "", error: false }); const [working, setWorking] = useState("");
  const getMarketData = useCallback(async () => {
    const [marketResponse, tradesResponse] = await Promise.all([
      fetch(`/api/center/trades/market?centerId=${buyerCenterId}`, { cache: "no-store" }),
      fetch(`/api/center/trades?centerId=${buyerCenterId}`, { cache: "no-store" }),
    ]);
    const [market, trades] = await Promise.all([marketResponse.json(), tradesResponse.json()]);
    if (!marketResponse.ok) throw new Error(market.message);
    if (!tradesResponse.ok) throw new Error(trades.message);
    return { listings: market.listings.filter((listing) => listing.center.id === sellerCenterId), trades: trades.trades.filter((trade) => trade.sellerCenterId === sellerCenterId) };
  }, [buyerCenterId, sellerCenterId]);
  useEffect(() => { getMarketData().then((marketData) => setData(marketData)).catch((error) => setMessage({ text: error.message, error: true })); }, [getMarketData]);
  function formFor(key, defaults = {}) { return forms[key] || defaults; }
  function setField(key, field, value) { setForms((current) => ({ ...current, [key]: { ...current[key], [field]: value } })); }
  async function createTrade(listingId) {
    const quantity = formFor(`listing-${listingId}`).quantity;
    setWorking(`listing-${listingId}`); setMessage({ text: "", error: false });
    try { const response = await fetch("/api/center/trades", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listingId, quantity, centerId: buyerCenterId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setMessage({ text: result.message, error: false }); setData(await getMarketData()); } catch (error) { setMessage({ text: error.message, error: true }); } finally { setWorking(""); }
  }
  async function tradeAction(trade, action) {
    const defaults = { quantity: trade.finalQty || trade.requestedQty, proposedPrice: trade.proposedPrice || trade.listing.pricePerQuintal, negotiationNote: trade.negotiationNote || "" };
    const actorCenterId = ["GRANT_PHYSICAL_CHECK", "ACCEPT_SALE", "REJECT_SALE"].includes(action) ? trade.sellerCenterId : trade.buyerCenterId;
    setWorking(`${trade.id}-${action}`); setMessage({ text: "", error: false });
    try { const response = await fetch(`/api/center/trades/${trade.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...formFor(trade.id, defaults), centerId: actorCenterId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setMessage({ text: result.message, error: false }); setData(await getMarketData()); } catch (error) { setMessage({ text: error.message, error: true }); } finally { setWorking(""); }
  }
  const gradeGroups = Object.entries(data.listings.reduce((groups, listing) => { (groups[listing.grade] ||= []).push(listing); return groups; }, {}));
  const sellerName = data.listings[0]?.center.name || data.trades[0]?.sellerCenter.name || "Selected center";
  return <><LoggedInNavbar /><main className="min-h-screen bg-[#f6f8f4] p-5 sm:p-8"><div className="mx-auto max-w-6xl"><Link href={`/admin/centers/${buyerCenterId}`} className="inline-flex items-center gap-2 text-sm font-bold text-green-800"><ArrowLeft size={16} />Back to buying center dashboard</Link><p className="mt-5 text-xs font-bold tracking-wider text-green-700">CENTER-TO-CENTER MARKETPLACE</p><h1 className="mt-1 text-3xl font-black">{sellerName} soybean stock</h1><p className="mt-2 text-gray-600">View all available stock grade-wise. The buying center reserves a lot, requests physical check, negotiates quantity and price, then the selling center confirms or cancels.</p>{message.text && <p className={`mt-5 rounded-xl p-3 font-bold ${message.error ? "bg-red-50 text-red-700" : "bg-green-50 text-green-800"}`}>{message.text}</p>}
    <section className="mt-7"><h2 className="text-2xl font-black">Available soybean by grade</h2><div className="mt-4 space-y-5">{gradeGroups.map(([grade, listings]) => <div key={grade}><h3 className="mb-2 text-lg font-black text-green-800">Grade {grade}</h3><div className="grid gap-4 md:grid-cols-2">{listings.map((listing) => { const available = Number(listing.availableQty) - Number(listing.reservedQty); const form = formFor(`listing-${listing.id}`); return <article key={listing.id} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-2xl font-black">{format(available)} qtl</p><p className="mt-1 font-bold text-green-800">₹{format(listing.pricePerQuintal)} / quintal</p><p className="mt-2 text-sm text-gray-600">Order by {new Date(listing.availableUntil).toLocaleDateString("en-IN")} · Pickup {new Date(listing.pickupStart).toLocaleDateString("en-IN")} – {new Date(listing.pickupEnd).toLocaleDateString("en-IN")}</p><div className="mt-4 flex gap-2"><input min="0.01" max={available} step="0.01" type="number" value={form.quantity || ""} onChange={(event) => setField(`listing-${listing.id}`, "quantity", event.target.value)} placeholder="Quantity (qtl)" className="min-w-0 flex-1 rounded-lg border p-2" /><button disabled={working === `listing-${listing.id}`} onClick={() => createTrade(listing.id)} className="rounded-lg bg-green-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">{working === `listing-${listing.id}` ? "Sending…" : "Order request"}</button></div></article>; })}</div></div>)}</div>{!gradeGroups.length && <p className="rounded-2xl bg-white p-6 text-gray-600 shadow-sm">This center has no currently available soybean listing.</p>}</section>
    <section className="mt-8"><h2 className="text-2xl font-black">Requests and settlement for this center pair</h2><p className="mt-1 text-sm text-gray-600">Admin can complete each side&apos;s action from this screen. Settlement updates both payment histories and both center storage totals.</p><div className="mt-4 space-y-4">{data.trades.map((trade) => { const tradeForm = formFor(trade.id, { quantity: trade.finalQty || trade.requestedQty, proposedPrice: trade.proposedPrice || trade.listing.pricePerQuintal, negotiationNote: trade.negotiationNote || "" }); return <article key={trade.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black">Grade {trade.listing.grade} · {format(trade.finalQty || trade.requestedQty)} qtl</p><p className="mt-1 text-sm text-gray-600">{trade.proposedPrice ? `Buyer offer ₹${format(trade.proposedPrice)} / qtl` : "No final price offer yet"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${trade.status === "PAID" ? "bg-green-100 text-green-800" : trade.status === "CANCELLED" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800"}`}>{statusLabel[trade.status]}</span></div>{trade.negotiationNote && <p className="mt-3 rounded-lg bg-gray-50 p-3 text-sm">Negotiation note: {trade.negotiationNote}</p>}
      {trade.status === "ORDERED" && <div className="mt-4 flex flex-wrap gap-2"><button disabled={working === `${trade.id}-REQUEST_PHYSICAL_CHECK`} onClick={() => tradeAction(trade, "REQUEST_PHYSICAL_CHECK")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><ClipboardCheck size={16} />Request physical check</button><button onClick={() => tradeAction(trade, "CANCEL")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Buyer center cancel</button></div>}
      {trade.status === "PHYSICAL_CHECK_PENDING" && <div className="mt-4 flex flex-wrap gap-2"><button disabled={working === `${trade.id}-GRANT_PHYSICAL_CHECK`} onClick={() => tradeAction(trade, "GRANT_PHYSICAL_CHECK")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><CheckCircle2 size={16} />Seller allows physical check</button><button onClick={() => tradeAction(trade, "REJECT_SALE")} className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700"><XCircle size={16} />Seller cancels</button><button onClick={() => tradeAction(trade, "CANCEL")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Buyer cancels</button></div>}
      {trade.status === "PHYSICAL_CHECKED" && <div className="mt-4 rounded-xl bg-green-50 p-4"><p className="font-bold text-green-900">Physical check completed — submit buyer center&apos;s final quantity and price.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><input min="0.01" step="0.01" type="number" value={tradeForm.quantity} onChange={(event) => setField(trade.id, "quantity", event.target.value)} placeholder="Final quantity" className="rounded-lg border bg-white p-2" /><input min="0.01" step="0.01" type="number" value={tradeForm.proposedPrice} onChange={(event) => setField(trade.id, "proposedPrice", event.target.value)} placeholder="Price / qtl" className="rounded-lg border bg-white p-2" /><input value={tradeForm.negotiationNote} onChange={(event) => setField(trade.id, "negotiationNote", event.target.value)} placeholder="Negotiation note" className="rounded-lg border bg-white p-2" /></div><div className="mt-3 flex gap-2"><button disabled={working === `${trade.id}-SUBMIT_OFFER`} onClick={() => tradeAction(trade, "SUBMIT_OFFER")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><Handshake size={16} />Submit buyer offer</button><button onClick={() => tradeAction(trade, "CANCEL")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Buyer cancels</button></div></div>}
      {trade.status === "CONFIRMED" && <div className="mt-4 flex flex-wrap gap-2"><button disabled={working === `${trade.id}-ACCEPT_SALE`} onClick={() => tradeAction(trade, "ACCEPT_SALE")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white"><CheckCircle2 size={16} />Seller confirms & settles</button><button onClick={() => tradeAction(trade, "REJECT_SALE")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Seller cancels offer</button><button onClick={() => tradeAction(trade, "CANCEL")} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Buyer cancels</button></div>}
      {trade.status === "PAID" && <p className="mt-4 rounded-lg bg-green-50 p-3 text-sm font-bold text-green-800">Settlement successful. Both centers&apos; payment histories, inventory listing, and used storage have been updated.</p>}</article>; })}</div>{!data.trades.length && <p className="mt-4 rounded-2xl bg-white p-6 text-gray-600 shadow-sm">No order request between these two centers yet.</p>}</section>
  </div></main></>;
}
