CREATE TYPE "public"."BuyerType" AS ENUM ('PROCESSOR', 'WHOLESALER', 'RETAILER', 'EXPORTER');
CREATE TYPE "public"."BuyerOrderStatus" AS ENUM ('ORDERED', 'PHYSICAL_CHECK_PENDING', 'PHYSICAL_CHECKED', 'CONFIRMED', 'CANCELLED', 'PAID');

CREATE TABLE "public"."Buyer" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "buyerType" "public"."BuyerType" NOT NULL, "businessName" TEXT NOT NULL, "gstin" TEXT NOT NULL, "panNumber" TEXT NOT NULL, "address" TEXT NOT NULL, "city" TEXT NOT NULL, "state" TEXT NOT NULL, "pinCode" CHAR(6) NOT NULL, "verificationStatus" "public"."VerificationStatus" NOT NULL DEFAULT 'PENDING', CONSTRAINT "Buyer_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Buyer_userId_key" ON "public"."Buyer"("userId"); CREATE UNIQUE INDEX "Buyer_gstin_key" ON "public"."Buyer"("gstin");
ALTER TABLE "public"."Buyer" ADD CONSTRAINT "Buyer_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "public"."BuyerVerificationRequest" ("id" TEXT NOT NULL, "buyerId" TEXT NOT NULL, "status" "public"."VerificationRequestStatus" NOT NULL DEFAULT 'PENDING', "note" TEXT, "adminNote" TEXT, "reviewedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reviewedAt" TIMESTAMP(3), CONSTRAINT "BuyerVerificationRequest_pkey" PRIMARY KEY ("id"));
CREATE INDEX "BuyerVerificationRequest_buyerId_status_idx" ON "public"."BuyerVerificationRequest"("buyerId", "status");
ALTER TABLE "public"."BuyerVerificationRequest" ADD CONSTRAINT "BuyerVerificationRequest_buyerId_fkey" FOREIGN KEY ("buyerId") REFERENCES "public"."Buyer"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "public"."BuyerVerificationRequest" ADD CONSTRAINT "BuyerVerificationRequest_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "public"."CenterListing" ("id" TEXT NOT NULL, "centerId" TEXT NOT NULL, "crop" "public"."CropType" NOT NULL DEFAULT 'SOYBEAN', "grade" "public"."Grade" NOT NULL, "availableQty" DECIMAL(10,2) NOT NULL, "reservedQty" DECIMAL(10,2) NOT NULL DEFAULT 0, "pricePerQuintal" DECIMAL(10,2) NOT NULL, "storageCharge" DECIMAL(10,2) NOT NULL DEFAULT 0, "handlingCharge" DECIMAL(10,2) NOT NULL DEFAULT 0, "gstRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "availableUntil" TIMESTAMP(3) NOT NULL, "pickupStart" TIMESTAMP(3) NOT NULL, "pickupEnd" TIMESTAMP(3) NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CenterListing_pkey" PRIMARY KEY ("id"));
ALTER TABLE "public"."CenterListing" ADD CONSTRAINT "CenterListing_centerId_fkey" FOREIGN KEY ("centerId") REFERENCES "public"."Center"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "public"."BuyerOrder" ("id" TEXT NOT NULL, "buyerId" TEXT NOT NULL, "listingId" TEXT NOT NULL, "requestedQty" DECIMAL(10,2) NOT NULL, "finalQty" DECIMAL(10,2), "deliveryAddress" TEXT NOT NULL, "status" "public"."BuyerOrderStatus" NOT NULL DEFAULT 'ORDERED', "inspectionNote" TEXT, "cancelReason" TEXT, "paymentConfirmedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BuyerOrder_pkey" PRIMARY KEY ("id"));
CREATE INDEX "BuyerOrder_buyerId_createdAt_idx" ON "public"."BuyerOrder"("buyerId", "createdAt"); CREATE INDEX "BuyerOrder_listingId_status_idx" ON "public"."BuyerOrder"("listingId", "status");
ALTER TABLE "public"."BuyerOrder" ADD CONSTRAINT "BuyerOrder_buyerId_fkey" FOREIGN KEY ("buyerId") REFERENCES "public"."Buyer"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "public"."BuyerOrder" ADD CONSTRAINT "BuyerOrder_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "public"."CenterListing"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
