"use client";

import { useEffect, useState } from "react";
import { LoggedInNavbar } from "../../../component/LoggedInNavbar";

const initial = { name: "RABI", year: "2026-27", startDate: "", endDate: "" };

export default function AdminSeasonsPage() {
  const [seasons, setSeasons] = useState([]), [form, setForm] = useState(initial), [message, setMessage] = useState("");
  const load = () => fetch("/api/admin/seasons", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); setSeasons(data.seasons); }).catch((error) => setMessage(error.message));
  useEffect(() => { load(); }, []);
  async function create(event) { event.preventDefault(); setMessage(""); const response = await fetch("/api/admin/seasons", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) setMessage(data.message); else { setForm(initial); load(); } }
  async function action(id, action) { const response = await fetch(`/api/admin/seasons/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const data = await response.json(); if (!response.ok) setMessage(data.message); else load(); }
  return <><LoggedInNavbar /><main className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-black">Season management</h1><p className="mt-2 text-gray-600">Create future seasons. Activating one automatically closes the previous active season.</p>{message && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-amber-800">{message}</p>}<form onSubmit={create} className="mt-6 grid gap-3 rounded-2xl bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-5"><select value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-lg border px-3 py-2"><option value="KHARIF">Kharif</option><option value="RABI">Rabi</option><option value="ZAID">Zaid</option></select><input required value={form.year} onChange={(e) => setForm({ ...form, year: e.target.value })} placeholder="Year e.g. 2026-27" className="rounded-lg border px-3 py-2" /><input required type="date" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} className="rounded-lg border px-3 py-2" /><input required type="date" value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} className="rounded-lg border px-3 py-2" /><button className="rounded-lg bg-green-700 px-4 py-2 font-bold text-white">Create season</button></form><div className="mt-6 space-y-3">{seasons.map((season) => <article key={season.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-5 shadow-sm"><div><h2 className="font-black">{season.name} {season.year}</h2><p className="mt-1 text-sm text-gray-600">{new Date(season.startDate).toLocaleDateString("en-IN")} – {new Date(season.endDate).toLocaleDateString("en-IN")} · {season._count.registrations} registrations</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${season.status === "ACTIVE" ? "bg-green-100 text-green-800" : season.status === "CLOSED" ? "bg-gray-100 text-gray-700" : "bg-amber-100 text-amber-800"}`}>{season.status}</span>{season.status !== "ACTIVE" && season.status !== "CLOSED" && <button onClick={() => action(season.id, "ACTIVATE")} className="rounded-lg bg-green-700 px-3 py-2 text-sm font-bold text-white">Activate</button>}{season.status === "ACTIVE" && <button onClick={() => action(season.id, "CLOSE")} className="rounded-lg border px-3 py-2 text-sm font-bold">Close</button>}</div></article>)}</div></div></main></>;
}
