"use client";

import Link from "next/link";
import { ArrowLeft, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { LoggedInNavbar } from "../../component/LoggedInNavbar";

const crops = ["Wheat", "Rice", "Maize", "Mustard", "Gram", "Soybean", "Cotton", "Bajra", "Jowar", "Potato", "Onion", "Tomato", "Sugarcane", "Other"];
const empty = { cropName: "Wheat", variety: "", area: "", unit: "ACRE", sowingDate: "", irrigation: "Rainfed", seedSource: "", expectedHarvestDate: "" };
const field = "mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5";
const formatSeason = (season) => `${season.name[0]}${season.name.slice(1).toLowerCase()} ${season.year}`;

export default function SeasonRegistrationPage() {
  const [data, setData] = useState(null), [form, setForm] = useState(empty), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const load = () => fetch("/api/season/current", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.message); setData(body); }).catch((err) => setError(err.message));
  useEffect(() => { load(); }, []);
  async function addCrop(event) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/season/crops", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.message); setForm(empty); load(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function removeCrop(id) { if (!window.confirm("Remove this crop declaration?")) return; const response = await fetch(`/api/season/crops/${id}`, { method: "DELETE" }); if (response.ok) load(); else { const body = await response.json(); setError(body.message); } }
  async function submitRegistration() { setSaving(true); setError(""); try { const response = await fetch("/api/season/submit", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.message); load(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  if (!data && !error) return <main className="grid min-h-screen place-items-center font-bold">Loading season…</main>;
  if (error && !data) return <main className="grid min-h-screen place-items-center p-6"><div><p className="text-red-700">{error}</p><Link href="/dashboard" className="mt-3 inline-block font-bold text-green-700">Back to dashboard</Link></div></main>;
  if (!data?.season) return <><LoggedInNavbar /><main className="mx-auto max-w-xl p-8"><h1 className="text-3xl font-black">No active season</h1><p className="mt-2 text-gray-600">Seasonal crop declaration will appear here when an admin activates a season.</p></main></>;
  const registration = data.registration, editable = registration.status === "DRAFT" || registration.status === "REJECTED";
  const declared = registration.crops.reduce((total, crop) => total + crop.area * (crop.unit === "HECTARE" ? 2.47105 : 1), 0), owned = data.farmer.landArea * (data.farmer.landUnit === "Hectare" ? 2.47105 : 1);
  return <><LoggedInNavbar /><main className="min-h-screen bg-gray-50 p-5 sm:p-8"><div className="mx-auto max-w-4xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-green-700"><ArrowLeft size={16} />Dashboard</Link><section className="mt-4 rounded-2xl bg-green-900 p-6 text-white"><p className="text-xs font-bold tracking-wider text-lime-300">ACTIVE SEASON</p><h1 className="mt-2 text-3xl font-black">{formatSeason(data.season)} crop declaration</h1><p className="mt-2 text-green-100">Land owned: {data.farmer.landArea} {data.farmer.landUnit} · Declared: {declared.toFixed(2)} Acre · Remaining: {Math.max(0, owned - declared).toFixed(2)} Acre</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full bg-lime-300" style={{ width: `${Math.min(100, declared / owned * 100)}%` }} /></div></section>{error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}
    <section className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Declared crops</h2><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold">{registration.status}</span></div>{registration.crops.length === 0 ? <p className="mt-4 text-gray-600">No crops added yet.</p> : <div className="mt-4 space-y-3">{registration.crops.map((crop) => <article key={crop.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-gray-50 p-4"><div><p className="font-black">{crop.cropName}{crop.variety ? ` — ${crop.variety}` : ""}</p><p className="mt-1 text-sm text-gray-600">{crop.area} {crop.unit} · Sown {new Date(crop.sowingDate).toLocaleDateString("en-IN")} · Harvest {new Date(crop.expectedHarvestDate).toLocaleDateString("en-IN")}</p></div>{editable && <button type="button" onClick={() => removeCrop(crop.id)} className="rounded-lg p-2 text-red-700 hover:bg-red-50"><Trash2 size={18} /></button>}</article>)}</div>}</section>
    {editable && <form onSubmit={addCrop} className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Add crop</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-bold">Crop<select value={form.cropName} onChange={(e) => setForm({ ...form, cropName: e.target.value })} className={field}>{crops.map((crop) => <option key={crop}>{crop}</option>)}</select></label><label className="text-sm font-bold">Variety<input value={form.variety} onChange={(e) => setForm({ ...form, variety: e.target.value })} className={field} /></label><label className="text-sm font-bold">Area<input required min="0.01" step="0.01" type="number" value={form.area} onChange={(e) => setForm({ ...form, area: e.target.value })} className={field} /></label><label className="text-sm font-bold">Unit<select value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })} className={field}><option value="ACRE">Acre</option><option value="HECTARE">Hectare</option></select></label><label className="text-sm font-bold">Sowing date<input required type="date" value={form.sowingDate} onChange={(e) => setForm({ ...form, sowingDate: e.target.value })} className={field} /></label><label className="text-sm font-bold">Expected harvest<input required type="date" value={form.expectedHarvestDate} onChange={(e) => setForm({ ...form, expectedHarvestDate: e.target.value })} className={field} /></label><label className="text-sm font-bold">Irrigation<select value={form.irrigation} onChange={(e) => setForm({ ...form, irrigation: e.target.value })} className={field}><option>Rainfed</option><option>Drip irrigation</option><option>Sprinkler</option><option>Canal</option><option>Tube well</option></select></label><label className="text-sm font-bold">Seed source<input value={form.seedSource} onChange={(e) => setForm({ ...form, seedSource: e.target.value })} className={field} /></label></div><button disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-green-700 px-4 py-3 font-bold text-white disabled:opacity-50"><Plus size={18} />Add crop</button></form>}{editable && registration.crops.length > 0 && <button disabled={saving} onClick={submitRegistration} className="mt-5 w-full rounded-xl bg-green-900 py-3 font-bold text-white disabled:opacity-50">Submit declaration for admin review</button>}{registration.status === "REJECTED" && registration.remarks && <p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700"><b>Admin remark:</b> {registration.remarks}</p>}</div></main></>;
}
