"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, ClipboardCheck, XCircle } from "lucide-react";
import { LoggedInNavbar } from "../../../component/LoggedInNavbar";

const money = (value) => `₹${Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
function total(order) { const qty = Number(order.finalQty ?? order.requestedQty); const item = qty * Number(order.buyerProposedPrice ?? order.listing.pricePerQuintal); const storage = qty * Number(order.listing.storageCharge); const handling = qty * Number(order.listing.handlingCharge); const taxable = item + storage + handling; return { qty, amount: taxable * (1 + Number(order.listing.gstRate) / 100) }; }

export default function AdminBuyerOrdersPage() {
  const router = useRouter(); const [orders, setOrders] = useState([]); const [forms, setForms] = useState({}); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [workingId, setWorkingId] = useState("");
  async function load() { const response = await fetch("/api/admin/buyer-orders", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setOrders(data.orders); }
  useEffect(() => { let active = true; fetch("/api/me").then((response) => response.json()).then((data) => { if (data.user?.role !== "ADMIN") router.replace("/"); }).catch(() => router.replace("/")); fetch("/api/admin/buyer-orders", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); return data.orders; }).then((items) => { if (active) setOrders(items); }).catch((requestError) => { if (active) setError(requestError.message); }); return () => { active = false; }; }, [router]);
  function formFor(order) { return forms[order.id] || {}; }
  function setField(order, field, value) { setForms((current) => ({ ...current, [order.id]: { ...formFor(order), [field]: value } })); }
  async function update(order, action, payload = {}) { setWorkingId(order.id); setError(""); setMessage(""); try { const response = await fetch(`/api/admin/buyer-orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setMessage(data.message); await load(); } catch (requestError) { setError(requestError.message); } finally { setWorkingId(""); } }
  function reject(order) { const reason = window.prompt("Center rejection reason:"); if (reason === null) return; update(order, "REJECT_SALE", { reason }); }
  return <><LoggedInNavbar /><main className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold tracking-wider text-green-700">ADMIN WORKFLOW</p><h1 className="mt-1 text-3xl font-black">Buyer orders</h1><p className="mt-2 text-gray-600">Review buyer business details, complete physical checks, and confirm center sale settlement.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>}{message && <p className="mt-5 rounded-xl bg-green-50 p-3 font-bold text-green-800">{message}</p>}<div className="mt-6 space-y-5">{orders.map((order) => { const form = formFor(order); const invoice = total(order); return <article key={order.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">{order.listing.center.name} · Buyer order</h2><p className="mt-1 text-sm text-gray-600">Soybean grade {order.listing.grade} · {invoice.qty} quintal · {order.status.replaceAll("_", " ")}</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-black text-green-800">{order.status}</span></div><div className="mt-5 grid gap-4 rounded-xl bg-gray-50 p-4 md:grid-cols-3"><div><p className="font-black">{order.buyer.businessName}</p><p className="mt-1 text-sm">{order.buyer.user.name} · {order.buyer.user.phone}</p><p className="text-sm">{order.buyer.user.email || "No email"}</p><p className="mt-2 text-sm"><b>GSTIN:</b> {order.buyer.gstin}</p></div><div className="text-sm"><p><b>Buyer address:</b> {order.buyer.address}, {order.buyer.city}, {order.buyer.state} - {order.buyer.pinCode}</p><p className="mt-2"><b>Delivery address:</b> {order.deliveryAddress}</p></div><div className="text-sm"><p><b>Center:</b> {order.listing.center.address}, {order.listing.center.district}</p><p className="mt-2"><b>Buyer amount:</b> {money(invoice.amount)}</p><p><b>Price:</b> {money(order.listing.pricePerQuintal)} / qtl</p></div></div>{order.inspectionNote && <p className="mt-4 rounded-xl bg-violet-50 p-3 text-sm"><b>Physical check note:</b> {order.inspectionNote}</p>}{order.cancelReason && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800"><b>Cancellation reason:</b> {order.cancelReason}</p>}
      <div className="mt-5 flex flex-wrap gap-2">{order.status === "PHYSICAL_CHECK_PENDING" && <button disabled={workingId === order.id} onClick={() => update(order, "GRANT_PHYSICAL_CHECK")} className="inline-flex items-center gap-2 rounded-lg bg-violet-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><ClipboardCheck size={16} />Grant buyer physical-check permission</button>}{order.status === "CONFIRMED" && <><p className="rounded-lg bg-amber-50 px-3 py-2 text-sm font-bold text-amber-900">Buyer offer: {invoice.qty} qtl at {money(order.buyerProposedPrice)} / qtl{order.buyerNegotiationNote ? ` · ${order.buyerNegotiationNote}` : ""}</p><button disabled={workingId === order.id} onClick={() => update(order, "CONFIRM_SALE")} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 size={16} />Accept buyer offer & settle sale</button></>}{!["PAID", "CANCELLED"].includes(order.status) && <button disabled={workingId === order.id} onClick={() => reject(order)} className="inline-flex items-center gap-2 rounded-lg border border-red-300 px-4 py-2 text-sm font-bold text-red-700 disabled:opacity-50"><XCircle size={16} />Reject sale</button>}</div>{order.status === "PAID" && <p className="mt-4 font-bold text-green-800">✓ Center sale and buyer settlement successful on {new Date(order.paymentConfirmedAt).toLocaleString("en-IN")}</p>}</article>; })}{!orders.length && !error && <p className="rounded-2xl bg-white p-8 text-center text-gray-600 shadow-sm">No buyer orders yet.</p>}</div></div></main></>;
}
