"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ClipboardCheck, MapPin, XCircle } from "lucide-react";
import { LoggedInNavbar } from "../../../component/LoggedInNavbar";

const money = (value) => `₹${Number(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const statusText = { ORDERED: "Order placed — request physical check permission.", PHYSICAL_CHECK_PENDING: "Physical check permission requested — waiting for center approval.", PHYSICAL_CHECKED: "Physical check approved — inspect stock, then send quantity and price offer.", CONFIRMED: "Your offer is with the center — waiting for acceptance or rejection.", PAID: "Purchase settlement successful.", CANCELLED: "Order cancelled." };
function bill(order) { const qty = Number(order.finalQty ?? order.requestedQty); const listing = order.listing; const price = Number(order.buyerProposedPrice ?? listing.pricePerQuintal); const item = qty * price; const storage = qty * Number(listing.storageCharge); const handling = qty * Number(listing.handlingCharge); const taxable = item + storage + handling; return { qty, price, item, storage, handling, gst: taxable * Number(listing.gstRate) / 100, total: taxable * (1 + Number(listing.gstRate) / 100) }; }

export default function BuyerOrdersPage() {
  const [orders, setOrders] = useState([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [workingId, setWorkingId] = useState(""); const [offers, setOffers] = useState({});
  async function load() { const response = await fetch("/api/buyer/orders", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setOrders(data.orders); }
  useEffect(() => { let active = true; fetch("/api/buyer/orders", { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); return data.orders; }).then((items) => { if (active) setOrders(items); }).catch((requestError) => { if (active) setError(requestError.message); }); return () => { active = false; }; }, []);
  async function update(order, action, payload = {}) { setWorkingId(order.id); setError(""); setMessage(""); try { const response = await fetch(`/api/buyer/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setMessage(data.message); await load(); } catch (requestError) { setError(requestError.message); } finally { setWorkingId(""); } }
  function cancel(order) { const reason = window.prompt("Cancellation reason (optional):"); if (reason === null) return; update(order, "CANCEL", { reason }); }
  return <><LoggedInNavbar /><main className="min-h-screen bg-[#f6f8f4] p-5 sm:p-8"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold tracking-wider text-green-700">BUYER ACCOUNT</p><h1 className="mt-1 text-3xl font-black">My soybean orders</h1><p className="mt-2 text-gray-600">Request physical-check permission, inspect stock yourself, then negotiate quantity and price with the center.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>}{message && <p className="mt-5 rounded-xl bg-green-50 p-3 font-bold text-green-800">{message}</p>}<div className="mt-6 space-y-5">{orders.map((order) => { const invoice = bill(order); const offer = offers[order.id] || { quantity: String(order.finalQty ?? order.requestedQty), proposedPrice: String(order.listing.pricePerQuintal), negotiationNote: "" }; return <article key={order.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">{order.listing.center.name}</h2><p className="mt-1 flex items-center gap-1 text-sm text-gray-600"><MapPin size={14} />{order.listing.center.address}, {order.listing.center.district}, {order.listing.center.state}</p><p className="mt-3 font-bold">Soybean · Grade {order.listing.grade} · {invoice.qty} quintal</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${order.status === "PAID" ? "bg-green-100 text-green-800" : order.status === "CANCELLED" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800"}`}>{order.status.replaceAll("_", " ")}</span></div><p className="mt-4 rounded-xl bg-gray-50 p-3 text-sm font-bold text-gray-700">{statusText[order.status]}</p>{order.buyerNegotiationNote && <p className="mt-3 rounded-xl bg-violet-50 p-3 text-sm text-violet-900"><b>Your negotiation note:</b> {order.buyerNegotiationNote}</p>}{order.cancelReason && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800"><b>Cancellation reason:</b> {order.cancelReason}</p>}
      {["PHYSICAL_CHECKED", "CONFIRMED", "PAID"].includes(order.status) && <section className="mt-4 rounded-xl border border-green-200 p-4"><h3 className="font-black">Payment details</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><p>Crop value<br /><b>{money(invoice.item)}</b></p><p>Storage charge<br /><b>{money(invoice.storage)}</b></p><p>Handling charge<br /><b>{money(invoice.handling)}</b></p><p>GST ({order.listing.gstRate}%)<br /><b>{money(invoice.gst)}</b></p><p className="rounded-lg bg-green-50 p-3 text-lg font-black text-green-900">Final amount<br />{money(invoice.total)}</p></div>{order.status === "PAID" && <p className="mt-3 flex items-center gap-2 font-bold text-green-800"><CheckCircle2 size={17} />Settlement successful on {new Date(order.paymentConfirmedAt).toLocaleString("en-IN")}</p>}</section>}
      <div className="mt-4 flex flex-wrap gap-2">{order.status === "ORDERED" && <button disabled={workingId === order.id} onClick={() => update(order, "REQUEST_PHYSICAL_CHECK")} className="inline-flex items-center gap-2 rounded-lg bg-violet-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><ClipboardCheck size={16} />Request physical-check permission</button>}{order.status === "PHYSICAL_CHECKED" && <><input min="0.01" step="0.01" type="number" value={offer.quantity} onChange={(event) => setOffers({ ...offers, [order.id]: { ...offer, quantity: event.target.value } })} placeholder="Quantity" className="w-32 rounded-lg border px-3 py-2 text-sm" /><input min="0.01" step="0.01" type="number" value={offer.proposedPrice} onChange={(event) => setOffers({ ...offers, [order.id]: { ...offer, proposedPrice: event.target.value } })} placeholder="Your price / qtl" className="w-36 rounded-lg border px-3 py-2 text-sm" /><input value={offer.negotiationNote} onChange={(event) => setOffers({ ...offers, [order.id]: { ...offer, negotiationNote: event.target.value } })} placeholder="Negotiation note" className="min-w-48 rounded-lg border px-3 py-2 text-sm" /><button disabled={workingId === order.id} onClick={() => update(order, "SUBMIT_OFFER", offer)} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Send offer to center</button></>}{!["CONFIRMED", "PAID", "CANCELLED"].includes(order.status) && <button disabled={workingId === order.id} onClick={() => cancel(order)} className="inline-flex items-center gap-2 rounded-lg border border-red-300 px-4 py-2 text-sm font-bold text-red-700 disabled:opacity-50"><XCircle size={16} />Cancel order</button>}</div></article>; })}{!orders.length && !error && <p className="rounded-2xl bg-white p-8 text-center text-gray-600 shadow-sm">No buyer orders yet.</p>}</div></div></main></>;
}
